### ISSUE TITLE
The service "dtc_queue.manager.run.orm" has a dependency on a non-existent service "doctrine"

### ISSUE THREAD

**Issue by shfrancis** [mmucklo/DtcQueueBundle#68]
I get the following error when I run the command `bin/console cache:clear`

I am using mongo-odm.

  _The service "**dtc_queue.manager.run.orm**" has a dependency on a non-existent service "doctrine"._  

**Versions for packages:**
       

        "symfony/framework-bundle": "^4.0",
        "mmucklo/queue-bundle": "^4.5",
        "doctrine/mongodb-odm": "^1.2",
        "doctrine/mongodb-odm-bundle": "^3.4"

**<project_root>/config/packages/dtc_queue.yaml file:**
```
dtc_queue:
    # For full configuration options see:
    #   https://github.com/mmucklo/DtcQueueBundle/blob/master/Resources/doc/full-configuration.md
    manager:
        # This parameter is required and should typically be set to one of:
        #   [odm|orm|beanstalkd|rabbit_mq|redis]
        job: odm
    odm:
        # This is only necessary if still using an "odm" manager.
        #   It only needs to be modified if you want to use a different
        #   document manager than the default one
        #   (there is a similar parameter for entity_manager if you're
        #   using orm)
        #
        # If you don't use odm at all, this can safely be ignored or deleted
        document_manager: dtc_queue
    priority:
        max: 255
        direction: desc
```

**Document Manager configuration <project_root>/config/packages/doctrine_mongodb.yaml:**
  ```
document_managers:
        default:
            .....
        dtc_queue:
            connection: default
            mappings:
                App:
                    is_bundle: false
                    type: 'yml'
                    dir: '%kernel.project_dir%/src/Document'
                    prefix: 'App\Document\'
                DtcQueueBundle:
                    dir: Document/
                    type: annotation
```
