### ISSUE TITLE
Call to undefined method Dtc\QueueBundle\ODM\JobManager::pruneErroneousJobs()

### ISSUE THREAD

**Issue by kralos** [mmucklo/DtcQueueBundle#72]
| Q             | A             |
| ------------- | ------------- |
| Version       | 4.5.3         |
| Persistance   | ODM           |

config:

```yaml
dtc_queue:
    manager:
        job: odm
    timings:
        record: true
```

`console -v dtc:queue:prune error` causes `Call to undefined method Dtc\QueueBundle\ODM\JobManager::pruneErroneousJobs()`
