### ISSUE TITLE
Call to undefined method Dtc\QueueBundle\ODM\RunManager::pruneJobTimings()

### ISSUE THREAD

**Issue by kralos** [mmucklo/DtcQueueBundle#73]
| Q             | A             |
| ------------- | ------------- |
| Version       | 4.5.3         |
| Persistance   | ODM           |

config:

```yaml
dtc_queue:
    manager:
        job: odm
    timings:
        record: true
```
`console -v dtc:queue:prune old_job_timings --older '2018-06-12'` causes `Call to undefined method Dtc\QueueBundle\ODM\RunManager::pruneJobTimings()`
