### ISSUE TITLE
Can't use phpredis auth

### ISSUE THREAD

**Issue by Lobosque** [mmucklo/DtcQueueBundle#75]
Whenever I try to set phpreadis auth to anything other than `~`, I get the following error when trying to run any queue-related command:

```
Fatal error: Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Argument 2 passed to Symfony\Component\DependencyInjection\Definition::addMethodCall() must be of the type array, string given, called in /app/vendor/mmucklo/queue-bundle/DependencyInjection/Compiler/RedisCompilerPass.php on line 88 in /app/vendor/symfony/dependency-injection/Definition.php:349
Stack trace:
#0 /app/vendor/mmucklo/queue-bundle/DependencyInjection/Compiler/RedisCompilerPass.php(88): Symfony\Component\DependencyInjection\Definition->addMethodCall('auth', 'abc')
#1 /app/vendor/mmucklo/queue-bundle/DependencyInjection/Compiler/RedisCompilerPass.php(33): Dtc\QueueBundle\DependencyInjection\Compiler\RedisCompilerPass->processPhpRedis(Object(Symfony\Component\DependencyInjection\ContainerBuilder))
#2 /app/vendor/symfony/dependency-injection/Compiler/Compiler.php(95): Dtc\QueueBundle\DependencyInjection\Compiler\RedisCompilerPass->process(Object(Symfony\Component\DependencyInjection\ContainerBuilder))
#3 /app/vendor/symfony/dependency-inj in /app/vendor/symfony/dependency-injection/Definition.php on line 349
```

My configuration is:

```
    redis:
        phpredis:
            host: localhost
            port: 6379
            timeout: 0
            retry_interval: 20
            read_timeout: 0
            auth: abc
```

I'm not sure what is going on. It is somehow expecting an array but from what I can see from the bundle tests it should be a string.
