### ISSUE TITLE
Problem installing the bundle ...

### ISSUE THREAD

**Issue by teratux** [mmucklo/DtcQueueBundle#87]
Hello, I'm currently testing out the DtcQueueBundle in my Symfony 4.1 project to see if it suits my needs.  I'm following the configuration and installation guide for my Symfony version but there seems to be a problem with the mappings.   This is the output of the command that generates an error:

./bin/console doctrine:schema:update --dump-sql
`There is no column with name 'ended_at' on table 'dtc_queue_run_archive'.`

These are the relevant config files:
app/AppKernel.php:
```
...
...
            new \Dtc\GridBundle\DtcGridBundle(),
            new Dtc\QueueBundle\DtcQueueBundle()
...
...
```
app/config.yml:
```
imports:
...
...
    - { resource: "@DtcGridBundle/Resources/config/grid.yml" }
...
...
doctrine:
    orm:
          entity_managers:
                 default:
                        mappings:
                               DtcQueueBundle: ~
...
...
dtc_queue:
    default_manager: orm
    orm:
        entity_manager: default
    manager:
        run:  orm
        job:  orm
```
./bin/console doctrine:mapping:info | grep Dtc:
```
 [OK]   Dtc\QueueBundle\Entity\RunArchive
 [OK]   Dtc\QueueBundle\Entity\Run
 [OK]   Dtc\QueueBundle\Entity\JobTiming
 [OK]   Dtc\QueueBundle\Entity\JobArchive
 [OK]   Dtc\QueueBundle\Entity\Job
```

What am I doing wrong?
Thanks in advance

**Comment by teratux** [comment]
I noticed in the annotations of the Job, JobArchive, JobTiming, Run, RunArchive, BaseJob and BaseRun entities that the properties that have two words in them, like BaseJob::whenUs, don't have a _"name=''"_ mapping in them.  I added in this case a **name="when_us"** annotation and a similiar annotation in the other entities and the problem dissapeared.  I'm not fond of changing the source code in vendors and a solution to this problem could be that I override all base classes in my own bundle, but since I'm not going to extend any of them, can this problem be solved by adding this annotation in all properties that use compound names? Is this an issue?

Thanks

**Comment by mmucklo** [comment]
@teratux Thanks for the report.

Normally these are auto-converted between camelcase (whenUs) and snake case (when_us) when inserting into the database.  It may be there is some configuration setting that differs on your setup.  I'll try to check to see what it might be.

**Comment by mmucklo** [comment]
Looks like Doctrine has a naming strategy option: [http://doctrine-orm.readthedocs.io/projects/doctrine-orm/en/latest/reference/namingstrategy.html](http://doctrine-orm.readthedocs.io/projects/doctrine-orm/en/latest/reference/namingstrategy.html)

Okay it looks like I have that "naming strategy" option set on my machine and in the test code.

For my entity manager I have:

```yaml
doctrine:
    # ...
    orm:
        # ...
        naming_strategy: doctrine.orm.naming_strategy.underscore
```

However I think in your case you don't have that set, so therein is the problem.  As different naming strategies are possible, however it may be prudent for me to hard-code the names of the columns manually or at least figure out a way that the indexing would work independent of the naming strategy (which I think is what's causing the problem here).
